# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql2
  database: allourideas_development
  pool: 5
  timeout: 5000
  username: root
  password: password
  host: mysql.allourideas-apps.svc.cluster.local

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3

staging:
  <<: *default


cucumber:
  <<: *TEST
